name: Run Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install robotframework
        pip install robotframework-seleniumlibrary

    - name: Wait for Selenium to be ready
      run: sleep 15

    - name: Run complex_test
      run: |
        robot --variable BROWSER:chrome --variable REMOTE_URL:http://localhost:4444/wd/hub --variable HEADLESS:--headless --variable NO_SANDBOX:--no-sandbox --variable DISABLE_DEV_SHM:--disable-dev-shm-usage tests/complex_test.robot
    

    

