name: Run Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:

    - uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 120
        install-chromedriver: true
    
    
    - uses: browser-actions/setup-chrome@v1
    - run: chrome --version
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install robotframework
        pip install robotframework-seleniumlibrary

    - name: Wait for Selenium to be ready
      run: sleep 5

    - name: Run complex_test
      run: |
        robot  tests/complex_test.robot
    

    

